# Generated by Django 2.1.7 on 2019-04-04 02:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('yfp_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('mango_id', models.PositiveIntegerField()),
                ('hub_url', models.CharField(max_length=125)),
                ('first_name', models.CharField(max_length=125)),
                ('last_name', models.CharField(max_length=125)),
                ('fb_page', models.CharField(blank=True, max_length=125)),
                ('fb_group', models.CharField(blank=True, max_length=125)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('assigned_va', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
